function closeHud()
    print("closeHud")
    TriggerServerEvent("hp_hud:server:UpdateData", true)
end

function openHud()
    print("openHud")
    TriggerServerEvent("hp_hud:server:UpdateData", false)
end

function giveVehicleKey(plate)
    if Config.VehicleKeys.status then
        if Config.VehicleKeys.system == "qb" then
            TriggerEvent("vehiclekeys:client:SetOwner", string.upper(plate))
        else
            -- TriggerClientEvent("CustomVehicleKey", playerSource, plate)
        end
    end
end
